### ISSUE TITLE
Empty talk file name

### ISSUE THREAD

**Issue by joto** [mstock/RoomAssets-App-Sync#10]
For this talk here https://pretalx.com/fossgis2024/talk/JAS9RR/ the script generates this file name: `./Hörsaal_1_Audimax_1/21-Donnerstag/21-Donnerstag_1415_-_KI-Gebäudeerkennung_–_Deep-Learning-Modelle_zur_Aktualisierung_der_ALKIS-Gebäude_-_JAS9RR-981905/-Ev_ulR` 

A file name starting with a `-` is not great obviously.

**Comment by mstock** [comment]
This should work a bit better now, although I'm kind-of cheating since the script is now skipping the download if it cannot determine a usable (i.e. non-empty) filename from the end of the URL. Since these URLs usually reference a JavaScript/HTML-based slideshow, downloading probably would not make a lot of sense anyway since it would likely be missing referenced JavaScript and CSS files and likely also images.

**Comment by joto** [comment]
Okay. We'll see how this works in practice in the future. For now I am closing this as done. Thanks!
