### ISSUE TITLE
Date in directory tree

### ISSUE THREAD

**Issue by joto** [mstock/RoomAssets-App-Sync#4]
Currently we have the dates in ISO format in the directory tree. I am wondering if we want to have the week day instead or as an addition. It is much easier to remember that today is Thursday then know its the 7th of March. Not something we need to fix right away or so, just something to think about.

**Comment by mstock** [comment]
This should work since 0008ec0769 and be the default. There are also some related, new command line parameters now, using `--locale de-DE`, one can localize the weekday name in German, and `--day-strftime-pattern` and `--session-strftime-pattern` (which defaults to using the day strftime pattern as prefix) allow to use custom [strftime patterns](https://metacpan.org/pod/DateTime#strftime-Patterns) when formatting dates, so the ISO format can be overridden if wanted now.

**Comment by joto** [comment]
Wow. This is pretty amazing. Thanks!
