### ISSUE TITLE
Creating ZIP file?

### ISSUE THREAD

**Issue by joto** [mstock/RoomAssets-App-Sync#5]
Turns out that in our case we can not install the NextCloud client on the machines in the rooms. So I am thinking about a different solution: Create a ZIP file for every room/date pair with all the material for that day and room. Then put that on a web server for manual download.

Would creating ZIP files be something I should add to the code our something I should do outside?

If I do it outside it would be useful to have a return code from `room-assets-sync` indicating whether any of the files changed. Otherwise I'd run `room-assets-sync` every few minutes to be up-to-date and re-generate all the zip files every day. Or maybe somebody has a different idea how to solve this.

**Comment by mstock** [comment]
I'm a bit undecided about this. While doing it inside the application (which probably wouldn't be too hard, so I could likely implement that if it's considered useful) prevents users from having to reinvent the wheel if they need this, it's also a bit less flexible if one wants a different set of ZIP files or use a different archive format. So for now, I've added a new `--detailed-exitcode` parameter which makes the application return more information in the exit code (which still would be useful if ZIP files eventually would get created inside the application):
````
        --[no-]detailed-exitcode        Flag to indicate if the exit code
                                        should contain a summary of the sync
                                        statistics. If set, the exit code
                                        contains a bitmask with bit 0
                                        indicating success (0) or failure
                                        (1), bit 1 indicating if there was a
                                        new talk found (1) or not (0), bit 2
                                        if a new resource was downloaded (1)
                                        or not (0), bit 3 if an existing
                                        resource was updated (1) or not (0)
                                        and bit 4 if an existing talk was
                                        moved around (1) or not (0).
````
So in short, if the exit code is > 1 and < 255, something has changed and one might want to trigger some kind of post processing. 0 just means success, 1 indicates a runtime error and 255 seems to be returned by `App::Cmd` and seems to indicate an error with the provided parameters.

In addition, there's also a new `--print-statistics` parameter which prints some more information about the changes, like the number of new talks or new talk assets. This is printed in JSON format on STDOUT, so could be post-processed with e.g. `jq`.

Please note that together with these changes, I also renamed the command line tool to just `room-assets` and made `sync` a sub-command, so now it should be called as `./bin/room-assets sync`. This added a new dependency on `libmoosex-app-cmd-perl` but should allow me to introduce further sub-commands if needed without a later change in the command line interface.

An alternative idea I had regarding ZIP generation would be a web application which allows one to browse through the directory structure and which can also create ZIP files and return these. It's probably a bit too much though, but would avoid the creation and deletion of potentially many ZIP files that are never used since then this would be done on demand. Although probably not too hard, I've got no idea if I would be able to implement this in time, and it would also require to run this as a service, ideally behind a reverse proxy, which might over complicate things a bit.

**Comment by joto** [comment]
That exit code seems to be a bit over the top. If I need that kind of detailed information, I definitely would not want to use a shell script. If something needs that kind of detailed processing you probably also want to know which files were downloaded/moved/etc.

A simple 0 for "nothing done", 1 for "something changed" and >1 for error would probably be enough and easier to understand.

**Comment by mstock** [comment]
Ok, I've dropped the `--detailed-exitcode` parameter again, the script should now behave as suggested regarding exit codes even without a special parameter.

**Comment by joto** [comment]
Okay, thanks. I'll implement the zip code in a script around it. I will close this issue now. We'll see how it works out and come back to this if there are any problems.
