### ISSUE TITLE
Script dies after failed download

### ISSUE THREAD

**Issue by joto** [mstock/RoomAssets-App-Sync#6]
If a resource can not be downloaded the script [fails at line 342](
https://github.com/mstock/RoomAssets-App-Sync/blob/c4a108083fa5a6d10d82bba573777d4a8d820751/lib/RoomAssets/App/Command/sync.pm#L342) with `confess`.

This hould just print a warning instead an keep going. I have changed the `confess` into a `warn` locally, which works for the time being. But it would be better if we also print information about which talk lead to this problem so that it can be fixed.

Note that in this case the reason for the failure was a broken link to an external page, not something broken at pretalx.

**Comment by joto** [comment]
Works! Thank you.

**Comment by mstock** [comment]
You're welcome :). I just pushed another commit which now also prints some information about the talk, i.e. title and code, as suggested.

Regarding the link to an external page which did not work: I might eventually prevent this by default since one might not want this script to perform requests to other sites than the one from Pretalx. But I probably will not get around to do this in the next few days, and having the ability to download e.g. larger files that can't be uploaded to Pretalx from other hosts certainly is useful so I would not want to completely prevent this.
